name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v1.3.0
        with:
          deno-version: v1.1.0

      - name: Check formatting
        run: deno fmt --check

      - name: Run unit tests
        run: deno test src/

      - name: Run module tests
        run: echo "No module tests"
